[build-system]
requires = ["setuptools>=68.2.0", "pybind11>=3.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = {}

[tool.setuptools.package-data]
src = ["*.h"]

[tool.setuptools.dynamic]
version = { attr = "acbs.__meta_version__" }

[project]
name = "acbs"
dynamic = ["version"]
authors = [{ name = "liushuyu", email = "liushuyu@aosc.io" }]
description = "AOSC CI Building System"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.14"
dependencies = ["pyparsing>=2.4,<4"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Intended Audience :: Developers",
    "Operating System :: POSIX :: Linux",
]
urls = { "Repository" = "https://github.com/AOSC-Dev/acbs" }

[project.optional-dependencies]
logging = ["pexpect"]
dev = ["pyright", "ruff", "setuptools", "pybind11>=3.0.0", "pexpect"]

[tool.ruff]
line-length = 127
[tool.ruff.lint.mccabe]
max-complexity = 5

[tool.pyright]
pythonVersion = "3.14"
exclude = ["build", "dist", "venv", ".venv"]
