name: CI checks

on:
  push:
    branches: [ staging, production, dx ]
  pull_request:
    branches: [ staging, production ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"
        cache: 'pip' # caching pip dependencies
    - name: Install native dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y libapt-pkg-dev
        sudo snap install --classic astral-uv
    - name: Install dependencies
      run: |
        uv venv
        uv pip install '.[dev]'
    - name: Type checking using pyright
      run: uv run --extra=dev pyright
    - name: Lint with Ruff
      run: uv run --extra=dev ruff check --config 'output-format="github"'
    - name: Run unittests
      run: ARCH=amd64 uv run --extra=dev python -m unittest discover ./tests/
